=== sparks1372/quantumworkbench/src/main/resources/problem_spec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Problems">
        <xs:complexType>
    	<xs:sequence>
    		<xs:element name="prob" maxOccurs="unbounded" minOccurs="1">
    		    <xs:complexType>
			    	<xs:sequence>
			    		<xs:element name="Name" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
			    		<xs:element name="DefFile" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
			    		<xs:element name="Desc" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
			    	</xs:sequence>
			    </xs:complexType>
			</xs:element>
    	</xs:sequence>
    </xs:complexType>
    </xs:element>
</xs:schema>

=== sparks1372/quantumworkbench/quantumworkbench-sever/src/main/resources/Problems.xml
<?xml version="1.0" encoding="UTF-8"?>
<Problems xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.w3schools.com problem_spec.xsd">
    <prob>
        <Name>Deutsch Problem</Name>
        <DefFile>deutsch.xml</DefFile>
        <Desc>Deutsch</Desc>
    </prob>
    <prob>
        <Name>jac</Name>
        <DefFile>jac.xml</DefFile>
        <Desc>sfa</Desc>
    </prob>
    <prob>
        <Name>2 Qubit Quantum Fourier Transform</Name>
        <DefFile>qft2qubit.xml</DefFile>
        <Desc>Search for Quantum fourier transform acting on 2 qubits</Desc>
    </prob>
    <prob>
        <Name>Quantum Teleportation Algorithm</Name>
        <DefFile>Teleportation.xml</DefFile>
        <Desc>Search for the quantum teleportation algorithm</Desc>
    </prob>
    <prob>
        <Name>QFT+</Name>
        <DefFile>qftextra.xml</DefFile>
        <Desc>qft extra</Desc>
    </prob>
    <prob>
        <Name>First Hadamard</Name>
        <DefFile>firsthad.xml</DefFile>
        <Desc>A Hadamard gate on the first Qubit</Desc>
    </prob>
    <prob>
        <Name>First Pauli Z</Name>
        <DefFile>firstpauliz.xml</DefFile>
        <Desc>A Pauli Z gate on the first Qubit</Desc>
    </prob>
    <prob>
        <Name>First Pauli X</Name>
        <DefFile>firstpaulix.xml</DefFile>
        <Desc>A Pauli X gate on the first Qubit</Desc>
    </prob>
    <prob>
        <Name>3 Qubit Quantum Fourier Transform</Name>
        <DefFile>qft3qubit.xml</DefFile>
        <Desc>Search for the QFT on only 3 qubits</Desc>
    </prob>
    <prob>
        <Name>Full Max Problem</Name>
        <DefFile>fullmaxproblem.xml</DefFile>
        <Desc>The max problem with all 24 test cases included.</Desc>
    </prob>
    <prob>
        <Name>Final Pauli X</Name>
        <DefFile>finalpaulix.xml</DefFile>
        <Desc>A Pauli X gate on the final Qubit</Desc>
    </prob>
    <prob>
        <Name>Quantum Fourier Transform</Name>
        <DefFile>qft.xml</DefFile>
        <Desc>Search for the Quantum Fourier Transform</Desc>
    </prob>
    <prob>
        <Name>Full Max Problem 2</Name>
        <DefFile>fullmaxproblem2.xml</DefFile>
        <Desc>The max problem with all 24 test cases included.</Desc>
    </prob>
    <prob>
        <Name>Deutsch Jozsa</Name>
        <DefFile>deutschjosza.xml</DefFile>
        <Desc>Deutsch Jozsa problem for 2 and 3 qubits</Desc>
    </prob>
    <prob>
        <Name>hadcnot</Name>
        <DefFile>hadcnot.xml</DefFile>
        <Desc>Hadamard followed by controlled not - Entanglement</Desc>
    </prob>
</Problems>
